version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app:latest
        container_name: laravel_app
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=pgsql
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_SSLMODE=${DB_SSLMODE}
        volumes:
            - .:/var/www
        ports:
            - "9001:9001"
        networks:
            - app-network
        depends_on:
            - nginx

    nginx:
        image: nginx:latest
        container_name: nginx_container
        ports:
            - "3000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis_container
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
